### ISSUE TITLE
NameError when using cantango with Active Admin

### ISSUE THREAD

**Issue by prognostikos** [kristianmandrup/cantango#10]
Steps to reproduce:
1. rails new test (3.1.1)
2. edit Gemfile to include 'activeadmin' and 'cantango' (have tried both latest gems and latest git/master)
3. bundle install
4. bundle exec rails c

```
lib/cantango/rails/helpers/rest_helper.rb:7:in `class_eval': undefined local variable or method `delete_ActiveAdmin' for CanTango::Rails::Helpers::RestHelper:Module (NameError)
```

**Comment by kristianmandrup** [comment]
Thanks! Please try the latest push to _master_ branch. I've just added an option to filter out (exclude) a subset of models registered with cantango.

`CanTango.config.models.exclude ActiveAdmin` 

Or use a symbol or string, either CamelCase syntax, or lowercase with underscores.

`CanTango.config.models.exclude :active_admin`

<pre>
module CanTango
  class Configuration
    class Models
      ...

      def exclude *names
        @excluded = names.flatten.select_labels
      end

      def excluded
        @excluded ||= []
      end

      def available_models
        ar_models.map(&:name) - excluded.map {|m| m.to_s.camelize}
      end
</pre>


Hope that helps move you forward :)

PS: Also fixed the generated method name in rest helpers to underscore method name, from _delete_MyModel_ to _delete_my_model_

**Comment by prognostikos** [comment]
This works if I manually create a `config/initializers/cantango.rb` file with the following contents:

```
CanTango.config do |config|
  config.models.exclude 'ActiveAdmin', 'ActiveAdmin::Comment'
end
```

However this is a bit of a "chicken & egg" problem -- I can't run the `cantango:install` generator without manually creating the initializer file, and then the generator wants to overwrite the initializer file.

In addition (though I haven't gotten this far in my testing yet) I assume that the excludes above will prevent me from using cantango for access control for the admin comments...

**Comment by prognostikos** [comment]
And actually, just excluding `ActiveAdmin::Comment` works. So my first initializer file is 

```
CanTango.config do |config|
  config.models.exclude 'ActiveAdmin::Comment'
end
```

I guess this will be an issue when using cantango with any other gem that includes its own models

**Comment by kristianmandrup** [comment]
Well, it is the `engine.rb`file which includes the module `RestHelpers` into the base View and Controller classes to make the rest helper methods available for each registered model. You will still be able to use any models in permits etc. No problem. 

I should however enable "late loading" of the RestHelpers module, only including it when explicitly specifying to do so. This will allow the install generator to be run, no chicken-and-egg problem. I will make a fix for this ASAP.

**Comment by kristianmandrup** [comment]
Ah, actually you can prevent your auto-load problem with the config option:

`CanTango.config.autoload.models :off`

Try this!

**Comment by kristianmandrup** [comment]
The latest master no longer include the `RestHelper` module by default. You must now explicitly do this using:

`CanTango.config.enable_rest_helper` or `CanTango.config.enable_helpers :rest`

Thus you can now combine this auto_loading of models, simply like this:

<pre>
CanTango.config do |c|
  # other config options
  c.enable_rest_helper
end
</pre>

Now, the RestHelper inclusion should no longer interfere with any of the generators!

**Comment by prognostikos** [comment]
Great, this works perfectly. Thanks for the quick response.

**Comment by kristianmandrup** [comment]
Great to hear :) Now I'm looking forward to hear how you progress from there. 
Maybe look at the Scope API. It might be handy:

<pre>
scope_user :admin do |admin|
  if admin.can?(:edit, Article) || admin.can?(:read, Post)
    # do stuff
  end
  if admin.can? :delete, Article
    # delete link here
  end
end
</pre>


Also check out https://github.com/kristianmandrup/cantango/wiki/Model-AC-scopes which might also be useful in this context ;)

**Comment by kristianmandrup** [comment]
I encourage you to look at my _cantango_demo_ app which is well under way...
