### ISSUE TITLE
Please install sweetloader gem

### ISSUE THREAD

**Issue by jmif** [kristianmandrup/cantango#2]
In attempting to run a simple generator with both cantango and sweetloader installed with rails 3.1.0.rc6  I receive this error message

Please use the new 'sweetloader' gem
/Users/jamifsud/Programming/mfsPublic/vendor/bundle/ruby/1.8/gems/cantango-0.8.4/lib/cantango/api/aliases.rb:2: (eval):3:in `engines':  is not a class/module (TypeError)
    from /Users/jamifsud/Programming/mfsPublic/vendor/bundle/ruby/1.8/gems/cantango-0.8.4/lib/cantango/configuration.rb:46
    from /Users/jamifsud/Programming/mfsPublic/vendor/bundle/ruby/1.8/gems/cantango-0.8.4/lib/cantango.rb:20:in`config'
    from /Users/jamifsud/Programming/mfsPublic/vendor/bundle/ruby/1.8/gems/cantango-0.8.4/lib/cantango/rules/dsl.rb:5:in `included'
    from /Users/jamifsud/Programming/mfsPublic/vendor/bundle/ruby/1.8/gems/cantango-0.8.4/lib/cantango/rules.rb:5:in`include'
    from /Users/jamifsud/Programming/mfsPublic/vendor/bundle/ruby/1.8/gems/cantango-0.8.4/lib/cantango/rules.rb:5
    from /Users/jamifsud/Programming/mfsPublic/vendor/bundle/ruby/1.8/gems/cantango-0.8.4/lib/cantango/permits/permit.rb:96
    from (eval):1
    from /Users/jamifsud/Programming/mfsPublic/vendor/bundle/ruby/1.8/gems/cantango-0.8.4/lib/cantango/api/aliases.rb:1:in `eval'
    from /Users/jamifsud/Programming/mfsPublic/vendor/bundle/ruby/1.8/gems/cantango-0.8.4/lib/cantango/api/aliases.rb:2
    from /Users/jamifsud/Programming/mfsPublic/vendor/bundle/ruby/1.8/gems/cantango-0.8.4/lib/cantango/api/aliases.rb:1:in`each'
    from /Users/jamifsud/Programming/mfsPublic/vendor/bundle/ruby/1.8/gems/cantango-0.8.4/lib/cantango/api/aliases.rb:1
    from /Users/jamifsud/Programming/mfsPublic/vendor/bundle/ruby/1.8/gems/activesupport-3.1.0.rc6/lib/active_support/dependencies.rb:237:in `require'
    from /Users/jamifsud/Programming/mfsPublic/vendor/bundle/ruby/1.8/gems/activesupport-3.1.0.rc6/lib/active_support/dependencies.rb:237:in`require'
    from /Users/jamifsud/Programming/mfsPublic/vendor/bundle/ruby/1.8/gems/activesupport-3.1.0.rc6/lib/active_support/dependencies.rb:223:in `load_dependency'
    from /Users/jamifsud/Programming/mfsPublic/vendor/bundle/ruby/1.8/gems/activesupport-3.1.0.rc6/lib/active_support/dependencies.rb:636:in`new_constants_in'
    from /Users/jamifsud/Programming/mfsPublic/vendor/bundle/ruby/1.8/gems/activesupport-3.1.0.rc6/lib/active_support/dependencies.rb:223:in `load_dependency'
    from /Users/jamifsud/Programming/mfsPublic/vendor/bundle/ruby/1.8/gems/activesupport-3.1.0.rc6/lib/active_support/dependencies.rb:237:in`require'
    from /Users/jamifsud/Programming/mfsPublic/vendor/bundle/ruby/1.8/gems/cantango-0.8.4/lib/cantango.rb:29
    from /Library/Ruby/Gems/1.8/gems/bundler-1.0.17/lib/bundler/runtime.rb:68:in `require'
    from /Library/Ruby/Gems/1.8/gems/bundler-1.0.17/lib/bundler/runtime.rb:68:in`require'
    from /Library/Ruby/Gems/1.8/gems/bundler-1.0.17/lib/bundler/runtime.rb:66:in `each'
    from /Library/Ruby/Gems/1.8/gems/bundler-1.0.17/lib/bundler/runtime.rb:66:in`require'
    from /Library/Ruby/Gems/1.8/gems/bundler-1.0.17/lib/bundler/runtime.rb:55:in `each'
    from /Library/Ruby/Gems/1.8/gems/bundler-1.0.17/lib/bundler/runtime.rb:55:in`require'
    from /Library/Ruby/Gems/1.8/gems/bundler-1.0.17/lib/bundler.rb:120:in `require'
    from /Users/jamifsud/Programming/mfsPublic/config/application.rb:7
    from /Users/jamifsud/Programming/mfsPublic/vendor/bundle/ruby/1.8/gems/railties-3.1.0.rc6/lib/rails/commands.rb:21:in`require'
    from /Users/jamifsud/Programming/mfsPublic/vendor/bundle/ruby/1.8/gems/railties-3.1.0.rc6/lib/rails/commands.rb:21
    from script/rails:6:in `require'
    from script/rails:6

**Comment by jmif** [comment]
I should also say that I am using a nifty generator, I'd be happy to provide more information if you need any.

**Comment by jmif** [comment]
Click happy..  sorry.

**Comment by kristianmandrup** [comment]
I will look at it tonight. You could try using the master branch or one of the latest branches (not the "refactor_cache" branch) and see if that helps. You could also clone the repo locally and use the :path option in your Gemfile to point to your local repo and debug from there. Alternatively, try an earlier version of cantango until I fix this. Sorry.

**Comment by jmif** [comment]
Will do, thanks!

**Comment by kristianmandrup** [comment]
Ah, now I remember why u get this error. Recently sugar-high was updated where sweetloader and file_mutation were extracted as separate gems. CanTango apparently still tries to include 'sugr-high/class_ext' (where the 'sweetloader' functionality used to reside) and in its place, I simply left a message saying "Please use new sweetloader gem".

So... you could either enforce use of an older version of sugar-high from before sweetloader was totally extracted, or...

You can wait for the next release of CanTango. Apparently I tested CanTango with Gemfile.lock in place using an older version of sugar-high, hence I didn't catch this bug before release. Cheers!

**Comment by mochnatiy** [comment]
Hello!
I'm still getting this error:
(in aliases.rb:2) >> (eval):3:in `engines':  is not a class/module (TypeError)
when trying to execute 'install' generator
ruby 1.8.7 + rails 3.0.3 + cantango 0.8.6 + sugar-high 0.6.0.
What i doing wrong?

**Comment by kristianmandrup** [comment]
In the README at the outset, I clearly state that this gem has NOT been tested for Ruby 1.8.7. I think your ruby version is likely the problem. I've just updated the generator specs in my latest push and created a small demo app linking directly to the lastest version (my local version pushed to master), and I an run the install generator just fine.
You are most welcome to try and patch any of the code which currently makes it incompatible with Ruby 1.8.7. Try running some of the specs and see where it breaks down for Ruby 1.8+. Thanks.
