### ISSUE TITLE
Integration with Rolify

### ISSUE THREAD

**Issue by PendragonDevelopment** [kristianmandrup/cantango#24]
This isn't really an issue, per se, but how would CanTango interact/interfere with an app that uses Devise, CanCan, and Rolify? Would there be conflicts in role assignments or resource policies? I'm fairly new to the Rails ecosystem, and I've already had bad luck with some plugin conflicts - I just want to make sure I cover all my bases before going down a road too far.

Thanks!

**Comment by kristianmandrup** [comment]
Hi, I haven't heard about rolify before. I will check it out! You should check the cantango mailinglist. As I noted several times there, I recommend that anyone interested in cantango starts off using `cantango-permits`. The "old" cantango is not being maintained currently. The old CanTango wiki can still be useful for some guidance/overview though. CanTango was designed to make it easy to substitute the role system. By default, CanTango assumes a `has_role?` method, so this is fine. However CanTango currently only supports passing a string or symbol to `has_role?`not the extra scope argument.
If you are using `cantango-permits` you should use `cantango-roles`and here it should be pretty easy to extend the functionality to support rolify. Please look at the specs. I will see if I have time myself to look into it and make some further progress with cantango. Good luck!

**Comment by kristianmandrup** [comment]
https://github.com/kristianmandrup/cantango-roles/wiki/Roles-Configuration

Added a TODO

**Comment by kristianmandrup** [comment]
Override this method in `cantango-roles`. Not sure how the methods would/should get access to the scope. Currently the framework only expects to work with a subject (fx a user). 

``` ruby
module CanTango
  module Permit
    class Role < Base
      def valid_for? subject
        in_role? subject
      end

      def in_role? subject
        return subject.send(has_role_meth, role) if subject.respond_to? has_role_meth
        return subject.send(roles_list_meth).include? role if subject.respond_to? roles_list_meth
        false
      end
```

**Comment by kristianmandrup** [comment]
Come to think of it, in the `cantango-core` gem you can introduce your own helper methods that extract data from the options hash.

``` ruby
# cantango/ability.base.rb

module CanTango
  module Ability
    class Base
      include CanCan::Ability

      attr_reader :candidate, :options

      # Equivalent to a CanCan Ability#initialize call
      # which executes all the permission logic
      def initialize candidate, options = {}
        raise "Candidate must be something!" if !candidate
        @candidate, @options = candidate, options
        execute
      end

      def session
        @session ||= options[:session] || {} # seperate session cache for each type of user?
      end

      # define your own helper

      def role_scope
        @role_scope ||= options[:role_scope]
      end
```

and then

``` ruby
      def in_role? subject
        return subject.send(has_role_meth, role, role_scope) if subject.respond_to? has_role_meth
        return subject.send(roles_list_meth).include? role if subject.respond_to? roles_list_meth
        false
      end
```

And to use it:

``` ruby
user_can? :edit, Project, :role_scope => Forum.first
```

**Comment by PendragonDevelopment** [comment]
Wow. Thanks for all this! I'm not sure I completely understand any of it, but I'll wade through it a bit and see what I can figure out.

Thanks again!

**Comment by kristianmandrup** [comment]
If I was you I would fork cantango, then directly make these changes and debug from there until you make it fit your scenario. I would add an extra method to Cantango::Config called `#role_system_used` (or see current Config RoleSystem configuration code) and then tweak the ìn_role?` method something like this:

``` ruby
  def in_role? subject
      if Cantango.config.role_system_used == :rolify
        return subject.send(has_role_meth, role, role_scope) if subject.respond_to? has_role_meth
      else
       return subject.send(has_role_meth, role) if subject.respond_to? has_role_meth
      end
      return subject.send(roles_list_meth).include? role if subject.respond_to? roles_list_meth
      false
  end
```

Good luck! Please keep me posted with your progress and if you hit any walls ;) May the code be with u!

**Comment by kristianmandrup** [comment]
I just forked 3-4 gem gems the past 2 days and tweaked them all to play nice together and fit my special needs. Get used to it ;)
