### ISSUE TITLE
Gemspec with old helper locations

### ISSUE THREAD

**Issue by troyholder** [kristianmandrup/cantango#3]
Installing cantango with bundle results in:

> Using cantango (0.8.4) from git://github.com/kristianmandrup/cantango.git (at master) 
> cantango at /Users/user/.rvm/gems/ruby-1.9.2-p290\@rails-3.1/bundler/gems/cantango-4905226b0215 did not have a valid >gemspec.
> This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
> The validation message from Rubygems was:
> ["lib/cantango/rails/base_helpers.rb", "lib/cantango/rails/controller_helpers.rb", "lib/cantango/rails/view_helpers.rb"] are not files

Looks like the Gemspec should list these files in lib/cantango/rails/helpers.

**Comment by kristianmandrup** [comment]
The 0.8.5 release should fix this and a few other bugs. Let me know if you still have any issues.
