### ISSUE TITLE
Non-ActiveRecord support?

### ISSUE THREAD

**Issue by kbighorse** [kristianmandrup/cantango#8]
Just confirming that only ActiveRecord is currently supported.

**Comment by kristianmandrup** [comment]
No, we just currently only made specs covering Active Record. I don't see that we have any ORM specifics in this project. Please let me know if you have trouble configuring it for whatever ORM (data store) solution that you wanna use. I'm sure I can help you out!

**Comment by kbighorse** [comment]
Here's what gave me that impression: https://gist.github.com/1320155.  Let me know if I'm missing something.  I ended up going with Cancan's separate role model for now, we just have an admin role I want to support, but it could be more complex down the road.  We're using MongoMapper.

**Comment by kristianmandrup** [comment]
I just pushed a major adaptor refactor/improvement to the _adaptor_refactor_ branch:

https://github.com/kristianmandrup/cantango/tree/adapter_refactor

I hope that helps and provides something to build on. To use this, you would have to use a new configuaration param:

CanTango.config.orms = [:mongo_mapper] 

Note that it has been designed to potentially support an app with multiple ORMs running side-by-side ;)

I think it makes good sense to stick with CanCan as long as it is simple enough. Only consider CanTango as/if it gets more complex down the road...

**Comment by kbighorse** [comment]
Awesome, thank you for this!  I will circle back when this comes up again.
